### ISSUE TITLE
Application breaks after upgrade from 1.4.0 to 1.5.0

### ISSUE THREAD

**Issue by heikomat** [aurelia/templating-resources#311]
**I'm submitting a bug report**

* **Library Version:**
1.5.0

**Please tell us about your environment:**
* **Operating System:**
OSX 10.12.6

* **Node Version:**
7.10.0

* **NPM Version:**
4.2.0

* **JSPM OR Webpack AND Version**
??

* **Browser:**
all tested | Chrome 61

* **Language:**
TypeScript 2.5.3

**Current behavior:**
After upgrading `aurelia-templating-resources` to 1.5.0, one of my applications stopped working. I have no idea how or why, but after downgrading to 1.4.0, my applications works again.

The application doesn't start, and throws errors:
```
subscription.js:44 Uncaught TypeError: plugin.load is not a function
    at Module.<anonymous> (subscription.js:44)
    at subscription.js:44
    at on (subscription.js:44)
    at Module.callPlugin (subscription.js:44)
    at Module.fetch (subscription.js:44)
    at Module.check (subscription.js:44)
    at Module.enable (subscription.js:44)
    at Module.<anonymous> (subscription.js:44)
    at subscription.js:44
    at subscription.js:44
    at each (subscription.js:44)
    at Module.emit (subscription.js:44)
    at Module.check (subscription.js:44)
    at Module.enable (subscription.js:44)
    at Object.enable (subscription.js:44)
    at Module.callPlugin (subscription.js:44)
(anonymous) @ subscription.js:44
(anonymous) @ subscription.js:44
on @ subscription.js:44
callPlugin @ subscription.js:44
fetch @ subscription.js:44
check @ subscription.js:44
enable @ subscription.js:44
(anonymous) @ subscription.js:44
(anonymous) @ subscription.js:44
(anonymous) @ subscription.js:44
each @ subscription.js:44
emit @ subscription.js:44
check @ subscription.js:44
enable @ subscription.js:44
enable @ subscription.js:44
callPlugin @ subscription.js:44
fetch @ subscription.js:44
check @ subscription.js:44
enable @ subscription.js:44
enable @ subscription.js:44
(anonymous) @ subscription.js:44
(anonymous) @ subscription.js:44
each @ subscription.js:44
enable @ subscription.js:44
init @ subscription.js:44
(anonymous) @ subscription.js:44
setTimeout (async)
(anonymous) @ subscription.js:44
localRequire @ subscription.js:44
requirejs @ subscription.js:44
(anonymous) @ subscription.js:44
Promise._execute @ browser-raw.js:209
Promise._resolveFromExecutor @ xhr.js:35
Promise @ web_socket.js:1
DefaultLoader._import @ subscription.js:44
loadText @ subscription.js:44
loadTemplate @ subscription.js:44
fetch @ subscription.js:44
load @ subscription.js:44
(anonymous) @ subscription.js:44
(anonymous) @ subscription.js:44
on @ subscription.js:44
callPlugin @ subscription.js:44
fetch @ subscription.js:44
check @ subscription.js:44
enable @ subscription.js:44
(anonymous) @ subscription.js:44
(anonymous) @ subscription.js:44
(anonymous) @ subscription.js:44
each @ subscription.js:44
emit @ subscription.js:44
check @ subscription.js:44
enable @ subscription.js:44
enable @ subscription.js:44
callPlugin @ subscription.js:44
fetch @ subscription.js:44
check @ subscription.js:44
enable @ subscription.js:44
enable @ subscription.js:44
(anonymous) @ subscription.js:44
(anonymous) @ subscription.js:44
each @ subscription.js:44
enable @ subscription.js:44
init @ subscription.js:44
(anonymous) @ subscription.js:44
setTimeout (async)
(anonymous) @ subscription.js:44
localRequire @ subscription.js:44
requirejs @ subscription.js:44
(anonymous) @ subscription.js:44
Promise._execute @ browser-raw.js:209
Promise._resolveFromExecutor @ xhr.js:35
Promise @ web_socket.js:1
DefaultLoader._import @ subscription.js:44
loadTemplate @ subscription.js:44
ensureRegistryEntry @ subscription.js:44
loadViewFactory @ subscription.js:44
loadViewFactory @ subscription.js:44
load @ subscription.js:44
load @ subscription.js:44
load @ subscription.js:44
(anonymous) @ subscription.js:44
tryCatcher @ subscription.js:44
Promise._settlePromiseFromHandler @ xhr.js:64
Promise._settlePromise @ cors.js:31
Promise._settlePromise0 @ cors.js:77
Promise._settlePromises @ jsonp.js:64
Promise._fulfill @ jsonp.js:10
PromiseArray._resolve @ subscription.js:11
PromiseArray._promiseFulfilled @ subscription.js:29
Promise._settlePromise @ cors.js:37
Promise._settlePromise0 @ cors.js:77
Promise._settlePromises @ jsonp.js:64
(anonymous) @ client.js:6
Promise resolved (async)
schedule @ subscription.js:44
Async.settlePromises @ client.js:5
Promise._fulfill @ jsonp.js:12
Promise._resolveCallback @ event_source.js:88
(anonymous) @ xhr.js:36
(anonymous) @ subscription.js:44
execCb @ subscription.js:44
check @ subscription.js:44
enable @ subscription.js:44
init @ subscription.js:44
(anonymous) @ subscription.js:44
setTimeout (async)
(anonymous) @ subscription.js:44
localRequire @ subscription.js:44
requirejs @ subscription.js:44
(anonymous) @ subscription.js:44
Promise._execute @ browser-raw.js:209
Promise._resolveFromExecutor @ xhr.js:35
Promise @ web_socket.js:1
DefaultLoader.loadModule @ subscription.js:44
loadAllModules @ subscription.js:44
importViewResources @ subscription.js:44
(anonymous) @ subscription.js:44
tryCatcher @ subscription.js:44
Promise._settlePromiseFromHandler @ xhr.js:64
Promise._settlePromise @ cors.js:31
Promise._settlePromise0 @ cors.js:77
Promise._settlePromises @ jsonp.js:64
Promise._fulfill @ jsonp.js:10
PromiseArray._resolve @ subscription.js:11
PromiseArray._promiseFulfilled @ subscription.js:29
Promise._settlePromise @ cors.js:37
Promise._settlePromise0 @ cors.js:77
Promise._settlePromises @ jsonp.js:64
(anonymous) @ client.js:6
Promise resolved (async)
schedule @ subscription.js:44
Async.settlePromises @ client.js:5
Promise._fulfill @ jsonp.js:12
Promise._resolveCallback @ event_source.js:88
Promise._settlePromiseFromHandler @ xhr.js:76
Promise._settlePromise @ cors.js:31
Promise._settlePromiseCtx @ cors.js:69
(anonymous) @ to_json.js:9
Promise resolved (async)
schedule @ subscription.js:44
Async.invoke @ to_json.js:9
Promise._then @ set.js:15
Promise.then @ web_socket.js:47
_normalize @ subscription.js:44
(anonymous) @ subscription.js:44
loadResources @ subscription.js:44
(anonymous) @ subscription.js:44
next @ subscription.js:44
runTasks @ subscription.js:44
(anonymous) @ subscription.js:44
tryCatcher @ subscription.js:44
Promise._settlePromiseFromHandler @ xhr.js:64
Promise._settlePromise @ cors.js:31
Promise._settlePromise0 @ cors.js:77
Promise._settlePromises @ jsonp.js:64
(anonymous) @ client.js:6
Promise resolved (async)
schedule @ subscription.js:44
Async.settlePromises @ client.js:5
Promise._fulfill @ jsonp.js:12
Promise._resolveCallback @ xhr.js:6
Promise._settlePromiseFromHandler @ xhr.js:76
Promise._settlePromise @ cors.js:31
Promise._settlePromise0 @ cors.js:77
Promise._settlePromises @ jsonp.js:64
(anonymous) @ client.js:6
Promise resolved (async)
schedule @ subscription.js:44
Async.settlePromises @ client.js:5
Promise._fulfill @ jsonp.js:12
Promise._resolveCallback @ event_source.js:88
Promise._settlePromiseFromHandler @ xhr.js:76
Promise._settlePromise @ cors.js:31
Promise._settlePromiseCtx @ cors.js:69
(anonymous) @ to_json.js:9
Promise resolved (async)
schedule @ subscription.js:44
Async.invoke @ to_json.js:9
Promise._then @ set.js:15
Promise.then @ web_socket.js:47
(anonymous) @ subscription.js:44
tryCatcher @ subscription.js:44
Promise._settlePromiseFromHandler @ xhr.js:64
Promise._settlePromise @ cors.js:31
Promise._settlePromise0 @ cors.js:77
Promise._settlePromises @ jsonp.js:64
(anonymous) @ client.js:6
Promise resolved (async)
schedule @ subscription.js:44
Async.settlePromises @ client.js:5
Promise._fulfill @ jsonp.js:12
Promise._resolveCallback @ event_source.js:88
(anonymous) @ xhr.js:36
(anonymous) @ subscription.js:44
execCb @ subscription.js:44
check @ subscription.js:44
enable @ subscription.js:44
init @ subscription.js:44
(anonymous) @ subscription.js:44
setTimeout (async)
(anonymous) @ subscription.js:44
localRequire @ subscription.js:44
requirejs @ subscription.js:44
(anonymous) @ subscription.js:44
Promise._execute @ browser-raw.js:209
Promise._resolveFromExecutor @ xhr.js:35
Promise @ web_socket.js:1
DefaultLoader.loadModule @ subscription.js:44
_loadPlugin @ subscription.js:44
(anonymous) @ subscription.js:44
tryCatcher @ subscription.js:44
Promise._settlePromiseFromHandler @ xhr.js:64
Promise._settlePromise @ cors.js:31
Promise._settlePromiseCtx @ cors.js:69
(anonymous) @ to_json.js:9
Promise resolved (async)
schedule @ subscription.js:44
Async.invoke @ to_json.js:9
Promise._then @ set.js:15
Promise.then @ web_socket.js:47
loadPlugin @ subscription.js:44
next @ subscription.js:44
tryCatcher @ subscription.js:44
Promise._settlePromiseFromHandler @ xhr.js:64
Promise._settlePromise @ cors.js:31
Promise._settlePromise0 @ cors.js:77
Promise._settlePromises @ jsonp.js:64
(anonymous) @ client.js:6
Promise resolved (async)
schedule @ subscription.js:44
Async.settlePromises @ client.js:5
Promise._fulfill @ jsonp.js:12
Promise._resolveCallback @ event_source.js:88
Promise._settlePromiseFromHandler @ xhr.js:76
Promise._settlePromise @ cors.js:31
Promise._settlePromiseCtx @ cors.js:69
(anonymous) @ to_json.js:9
Promise resolved (async)
schedule @ subscription.js:44
Async.invoke @ to_json.js:9
Promise._then @ set.js:15
Promise.then @ web_socket.js:47
(anonymous) @ subscription.js:44
tryCatcher @ subscription.js:44
Promise._settlePromiseFromHandler @ xhr.js:64
Promise._settlePromise @ cors.js:31
Promise._settlePromise0 @ cors.js:77
Promise._settlePromises @ jsonp.js:64
(anonymous) @ client.js:6
Promise resolved (async)
schedule @ subscription.js:44
Async.settlePromises @ client.js:5
Promise._fulfill @ jsonp.js:12
Promise._resolveCallback @ event_source.js:88
(anonymous) @ xhr.js:36
(anonymous) @ subscription.js:44
execCb @ subscription.js:44
check @ subscription.js:44
enable @ subscription.js:44
init @ subscription.js:44
(anonymous) @ subscription.js:44
setTimeout (async)
(anonymous) @ subscription.js:44
localRequire @ subscription.js:44
requirejs @ subscription.js:44
(anonymous) @ subscription.js:44
Promise._execute @ browser-raw.js:209
Promise._resolveFromExecutor @ xhr.js:35
Promise @ web_socket.js:1
DefaultLoader.loadModule @ subscription.js:44
_loadPlugin @ subscription.js:44
(anonymous) @ subscription.js:44
tryCatcher @ subscription.js:44
Promise._settlePromiseFromHandler @ xhr.js:64
Promise._settlePromise @ cors.js:31
Promise._settlePromiseCtx @ cors.js:69
(anonymous) @ to_json.js:9
Promise resolved (async)
schedule @ subscription.js:44
Async.invoke @ to_json.js:9
Promise._then @ set.js:15
Promise.then @ web_socket.js:47
loadPlugin @ subscription.js:44
next @ subscription.js:44
tryCatcher @ subscription.js:44
Promise._settlePromiseFromHandler @ xhr.js:64
Promise._settlePromise @ cors.js:31
Promise._settlePromise0 @ cors.js:77
Promise._settlePromises @ jsonp.js:64
(anonymous) @ client.js:6
Promise resolved (async)
schedule @ subscription.js:44
Async.settlePromises @ client.js:5
Promise._fulfill @ jsonp.js:12
Promise._resolveCallback @ event_source.js:88
Promise._settlePromiseFromHandler @ xhr.js:76
Promise._settlePromise @ cors.js:31
Promise._settlePromiseCtx @ cors.js:69
(anonymous) @ to_json.js:9
Promise resolved (async)
schedule @ subscription.js:44
Async.invoke @ to_json.js:9
Promise._then @ set.js:15
Promise.then @ web_socket.js:47
(anonymous) @ subscription.js:44
tryCatcher @ subscription.js:44
Promise._settlePromiseFromHandler @ xhr.js:64
Promise._settlePromise @ cors.js:31
Promise._settlePromise0 @ cors.js:77
Promise._settlePromises @ jsonp.js:64
(anonymous) @ client.js:6
Promise resolved (async)
schedule @ subscription.js:44
Async.settlePromises @ client.js:5
Promise._fulfill @ jsonp.js:12
Promise._resolveCallback @ event_source.js:88
(anonymous) @ xhr.js:36
(anonymous) @ subscription.js:44
execCb @ subscription.js:44
check @ subscription.js:44
enable @ subscription.js:44
init @ subscription.js:44
(anonymous) @ subscription.js:44
setTimeout (async)
(anonymous) @ subscription.js:44
localRequire @ subscription.js:44
requirejs @ subscription.js:44
(anonymous) @ subscription.js:44
Promise._execute @ browser-raw.js:209
Promise._resolveFromExecutor @ xhr.js:35
Promise @ web_socket.js:1
DefaultLoader.loadModule @ subscription.js:44
_loadPlugin @ subscription.js:44
(anonymous) @ subscription.js:44
tryCatcher @ subscription.js:44
Promise._settlePromiseFromHandler @ xhr.js:64
Promise._settlePromise @ cors.js:31
Promise._settlePromiseCtx @ cors.js:69
(anonymous) @ to_json.js:9
Promise resolved (async)
schedule @ subscription.js:44
Async.invoke @ to_json.js:9
Promise._then @ set.js:15
Promise.then @ web_socket.js:47
loadPlugin @ subscription.js:44
next @ subscription.js:44
tryCatcher @ subscription.js:44
Promise._settlePromiseFromHandler @ xhr.js:64
Promise._settlePromise @ cors.js:31
Promise._settlePromise0 @ cors.js:77
Promise._settlePromises @ jsonp.js:64
(anonymous) @ client.js:6
Promise resolved (async)
schedule @ subscription.js:44
Async.settlePromises @ client.js:5
Promise._fulfill @ jsonp.js:12
Promise._resolveCallback @ event_source.js:88
Promise._settlePromiseFromHandler @ xhr.js:76
Promise._settlePromise @ cors.js:31
Promise._settlePromiseCtx @ cors.js:69
(anonymous) @ to_json.js:9
Promise resolved (async)
schedule @ subscription.js:44
Async.invoke @ to_json.js:9
Promise._then @ set.js:15
Promise.then @ web_socket.js:47
(anonymous) @ subscription.js:44
tryCatcher @ subscription.js:44
Promise._settlePromiseFromHandler @ xhr.js:64
Promise._settlePromise @ cors.js:31
Promise._settlePromise0 @ cors.js:77
Promise._settlePromises @ jsonp.js:64
(anonymous) @ client.js:6
Promise resolved (async)
schedule @ subscription.js:44
Async.settlePromises @ client.js:5
Promise._fulfill @ jsonp.js:12
Promise._resolveCallback @ event_source.js:88
(anonymous) @ xhr.js:36
(anonymous) @ subscription.js:44
execCb @ subscription.js:44
check @ subscription.js:44
enable @ subscription.js:44
init @ subscription.js:44
(anonymous) @ subscription.js:44
setTimeout (async)
(anonymous) @ subscription.js:44
localRequire @ subscription.js:44
requirejs @ subscription.js:44
(anonymous) @ subscription.js:44
Promise._execute @ browser-raw.js:209
Promise._resolveFromExecutor @ xhr.js:35
Promise @ web_socket.js:1
DefaultLoader.loadModule @ subscription.js:44
_loadPlugin @ subscription.js:44
(anonymous) @ subscription.js:44
tryCatcher @ subscription.js:44
Promise._settlePromiseFromHandler @ xhr.js:64
Promise._settlePromise @ cors.js:31
Promise._settlePromiseCtx @ cors.js:69
(anonymous) @ to_json.js:9
Promise resolved (async)
schedule @ subscription.js:44
Async.invoke @ to_json.js:9
Promise._then @ set.js:15
Promise.then @ web_socket.js:47
loadPlugin @ subscription.js:44
next @ subscription.js:44
tryCatcher @ subscription.js:44
Promise._settlePromiseFromHandler @ xhr.js:64
Promise._settlePromise @ cors.js:31
Promise._settlePromise0 @ cors.js:77
Promise._settlePromises @ jsonp.js:64
(anonymous) @ client.js:6
Promise resolved (async)
schedule @ subscription.js:44
Async.settlePromises @ client.js:5
Promise._fulfill @ jsonp.js:12
Promise._resolveCallback @ event_source.js:88
Promise._settlePromiseFromHandler @ xhr.js:76
Promise._settlePromise @ cors.js:31
Promise._settlePromiseCtx @ cors.js:69
(anonymous) @ to_json.js:9
Promise resolved (async)
schedule @ subscription.js:44
Async.invoke @ to_json.js:9
Promise._then @ set.js:15
Promise.then @ web_socket.js:47
(anonymous) @ subscription.js:44
tryCatcher @ subscription.js:44
Promise._settlePromiseFromHandler @ xhr.js:64
Promise._settlePromise @ cors.js:31
Promise._settlePromise0 @ cors.js:77
Promise._settlePromises @ jsonp.js:64
(anonymous) @ client.js:6
Promise resolved (async)
schedule @ subscription.js:44
Async.settlePromises @ client.js:5
Promise._fulfill @ jsonp.js:12
Promise._resolveCallback @ event_source.js:88
(anonymous) @ xhr.js:36
(anonymous) @ subscription.js:44
execCb @ subscription.js:44
check @ subscription.js:44
enable @ subscription.js:44
init @ subscription.js:44
(anonymous) @ subscription.js:44
setTimeout (async)
(anonymous) @ subscription.js:44
localRequire @ subscription.js:44
requirejs @ subscription.js:44
(anonymous) @ subscription.js:44
Promise._execute @ browser-raw.js:209
Promise._resolveFromExecutor @ xhr.js:35
Promise @ web_socket.js:1
DefaultLoader.loadModule @ subscription.js:44
_loadPlugin @ subscription.js:44
(anonymous) @ subscription.js:44
tryCatcher @ subscription.js:44
Promise._settlePromiseFromHandler @ xhr.js:64
Promise._settlePromise @ cors.js:31
Promise._settlePromiseCtx @ cors.js:69
(anonymous) @ to_json.js:9
Promise resolved (async)
schedule @ subscription.js:44
Async.invoke @ to_json.js:9
Promise._then @ set.js:15
Promise.then @ web_socket.js:47
loadPlugin @ subscription.js:44
next @ subscription.js:44
tryCatcher @ subscription.js:44
Promise._settlePromiseFromHandler @ xhr.js:64
Promise._settlePromise @ cors.js:31
Promise._settlePromise0 @ cors.js:77
Promise._settlePromises @ jsonp.js:64
(anonymous) @ client.js:6
publisher.js:37 Unhandled rejection Error: Load timeout for modules: template-registry-entry!aurelia-templating-resources/if.html_unnormalized2,template-registry-entry!aurelia-templating-resources/if.html,text!aurelia-templating-resources/if.html_unnormalized3,text!aurelia-templating-resources/if.html
http://requirejs.org/docs/errors.html#timeout
    at makeError (http://localhost:9000/scripts/vendor-bundle.js:3957:17)
    at checkLoaded (http://localhost:9000/scripts/vendor-bundle.js:4487:23)
    at http://localhost:9000/scripts/vendor-bundle.js:4508:25
From previous event:
    at DefaultLoader._import (http://localhost:9000/scripts/vendor-bundle.js:13803:14)
    at DefaultLoader.loadTemplate (http://localhost:9000/scripts/vendor-bundle.js:13770:19)
    at ensureRegistryEntry (http://localhost:9000/scripts/vendor-bundle.js:21772:19)
    at ViewEngine.loadViewFactory (http://localhost:9000/scripts/vendor-bundle.js:21840:14)
    at ConventionalViewStrategy.loadViewFactory (http://localhost:9000/scripts/vendor-bundle.js:19230:25)
    at HtmlBehaviorResource.load (http://localhost:9000/scripts/vendor-bundle.js:22619:29)
    at ResourceDescription.load (http://localhost:9000/scripts/vendor-bundle.js:21659:28)
    at ResourceModule.load (http://localhost:9000/scripts/vendor-bundle.js:21601:25)
    at http://localhost:9000/scripts/vendor-bundle.js:21971:43
From previous event:
    at ViewEngine.importViewResources (http://localhost:9000/scripts/vendor-bundle.js:21940:52)
    at http://localhost:9000/scripts/vendor-bundle.js:12870:25
From previous event:
    at loadResources (http://localhost:9000/scripts/vendor-bundle.js:12861:9)
    at http://localhost:9000/scripts/vendor-bundle.js:12938:16
    at next (http://localhost:9000/scripts/vendor-bundle.js:12818:32)
    at runTasks (http://localhost:9000/scripts/vendor-bundle.js:12824:12)
    at http://localhost:9000/scripts/vendor-bundle.js:13104:18
From previous event:
    at http://localhost:9000/scripts/vendor-bundle.js:13103:23
From previous event:
    at FrameworkConfiguration.apply (http://localhost:9000/scripts/vendor-bundle.js:13088:44)
    at Aurelia.start (http://localhost:9000/scripts/vendor-bundle.js:12704:39)
    at Object.configure (http://localhost:9000/scripts/app-bundle.js:85:17)
    at http://localhost:9000/scripts/vendor-bundle.js:11598:29
From previous event:
    at config (http://localhost:9000/scripts/vendor-bundle.js:11593:56)
    at http://localhost:9000/scripts/vendor-bundle.js:11629:14
From previous event:
    at bootstrap (http://localhost:9000/scripts/vendor-bundle.js:11628:26)
    at http://localhost:9000/scripts/vendor-bundle.js:11615:9
    at <anonymous>
From previous event:
    at run (http://localhost:9000/scripts/vendor-bundle.js:11610:61)
    at Object.<anonymous> (http://localhost:9000/scripts/vendor-bundle.js:11635:37)
    at Object.execCb (http://localhost:9000/scripts/vendor-bundle.js:5485:33)
    at Module.check (http://localhost:9000/scripts/vendor-bundle.js:4672:51)
    at Module.enable (http://localhost:9000/scripts/vendor-bundle.js:4965:22)
    at Object.enable (http://localhost:9000/scripts/vendor-bundle.js:5346:39)
    at Module.<anonymous> (http://localhost:9000/scripts/vendor-bundle.js:4950:33)
    at http://localhost:9000/scripts/vendor-bundle.js:3923:23
    at each (http://localhost:9000/scripts/vendor-bundle.js:3848:31)
    at Module.enable (http://localhost:9000/scripts/vendor-bundle.js:4902:17)
    at Module.init (http://localhost:9000/scripts/vendor-bundle.js:4577:26)
    at http://localhost:9000/scripts/vendor-bundle.js:5249:36
printWarning @ publisher.js:37
formatAndLogError @ uri.js:54
fireRejectionEvent @ uri.js:80
Promise._notifyUnhandledRejection @ browser-asap.js:42
(anonymous) @ logging.js:47
setTimeout (async)
(anonymous) @ logging.js:47
Promise resolved (async)
schedule @ subscription.js:44
Async.invokeLater @ logging.js:47
Promise._ensurePossibleRejectionHandled @ browser-asap.js:22
Promise._reject @ jsonp.js:30
Promise._settlePromise @ cors.js:47
Promise._settlePromise0 @ cors.js:77
Promise._settlePromises @ jsonp.js:61
(anonymous) @ client.js:6
Promise resolved (async)
schedule @ subscription.js:44
Async.settlePromises @ client.js:5
Promise._reject @ jsonp.js:28
Promise._settlePromise @ cors.js:47
Promise._settlePromise0 @ cors.js:77
Promise._settlePromises @ jsonp.js:61
(anonymous) @ client.js:6
Promise resolved (async)
schedule @ subscription.js:44
Async.settlePromises @ client.js:5
Promise._reject @ jsonp.js:28
Promise._settlePromise @ cors.js:47
Promise._settlePromise0 @ cors.js:77
Promise._settlePromises @ jsonp.js:61
(anonymous) @ client.js:6
Promise resolved (async)
schedule @ subscription.js:44
Async.settlePromises @ client.js:5
Promise._reject @ jsonp.js:28
Promise._settlePromise @ cors.js:47
Promise._settlePromise0 @ cors.js:77
Promise._settlePromises @ jsonp.js:61
(anonymous) @ client.js:6
Promise resolved (async)
schedule @ subscription.js:44
Async.settlePromises @ client.js:5
Promise._reject @ jsonp.js:28
Promise._rejectCallback @ xhr.js:26
(anonymous) @ xhr.js:38
(anonymous) @ subscription.js:44
(anonymous) @ subscription.js:44
each @ subscription.js:44
emit @ subscription.js:44
(anonymous) @ subscription.js:44
each @ subscription.js:44
onError @ subscription.js:44
checkLoaded @ subscription.js:44
(anonymous) @ subscription.js:44
setTimeout (async)
checkLoaded @ subscription.js:44
(anonymous) @ subscription.js:44
setTimeout (async)
checkLoaded @ subscription.js:44
(anonymous) @ subscription.js:44
setTimeout (async)
checkLoaded @ subscription.js:44
(anonymous) @ subscription.js:44
setTimeout (async)
checkLoaded @ subscription.js:44
(anonymous) @ subscription.js:44
setTimeout (async)
checkLoaded @ subscription.js:44
(anonymous) @ subscription.js:44
setTimeout (async)
checkLoaded @ subscription.js:44
(anonymous) @ subscription.js:44
setTimeout (async)
checkLoaded @ subscription.js:44
(anonymous) @ subscription.js:44
setTimeout (async)
checkLoaded @ subscription.js:44
(anonymous) @ subscription.js:44
setTimeout (async)
checkLoaded @ subscription.js:44
(anonymous) @ subscription.js:44
setTimeout (async)
checkLoaded @ subscription.js:44
(anonymous) @ subscription.js:44
setTimeout (async)
checkLoaded @ subscription.js:44
(anonymous) @ subscription.js:44
setTimeout (async)
checkLoaded @ subscription.js:44
(anonymous) @ subscription.js:44
setTimeout (async)
checkLoaded @ subscription.js:44
(anonymous) @ subscription.js:44
setTimeout (async)
checkLoaded @ subscription.js:44
(anonymous) @ subscription.js:44
setTimeout (async)
checkLoaded @ subscription.js:44
(anonymous) @ subscription.js:44
setTimeout (async)
checkLoaded @ subscription.js:44
(anonymous) @ subscription.js:44
setTimeout (async)
checkLoaded @ subscription.js:44
(anonymous) @ subscription.js:44
setTimeout (async)
checkLoaded @ subscription.js:44
(anonymous) @ subscription.js:44
setTimeout (async)
checkLoaded @ subscription.js:44
(anonymous) @ subscription.js:44
setTimeout (async)
checkLoaded @ subscription.js:44
(anonymous) @ subscription.js:44
setTimeout (async)
checkLoaded @ subscription.js:44
(anonymous) @ subscription.js:44
setTimeout (async)
checkLoaded @ subscription.js:44
(anonymous) @ subscription.js:44
setTimeout (async)
checkLoaded @ subscription.js:44
(anonymous) @ subscription.js:44
setTimeout (async)
checkLoaded @ subscription.js:44
(anonymous) @ subscription.js:44
setTimeout (async)
checkLoaded @ subscription.js:44
(anonymous) @ subscription.js:44
setTimeout (async)
checkLoaded @ subscription.js:44
(anonymous) @ subscription.js:44
publisher.js:37 Unhandled rejection Error: Load timeout for modules: template-registry-entry!aurelia-templating-resources/if.html_unnormalized2,template-registry-entry!aurelia-templating-resources/if.html,text!aurelia-templating-resources/if.html_unnormalized3,text!aurelia-templating-resources/if.html
http://requirejs.org/docs/errors.html#timeout
    at makeError (http://localhost:9000/scripts/vendor-bundle.js:3957:17)
    at checkLoaded (http://localhost:9000/scripts/vendor-bundle.js:4487:23)
    at http://localhost:9000/scripts/vendor-bundle.js:4508:25
From previous event:
    at DefaultLoader._import (http://localhost:9000/scripts/vendor-bundle.js:13803:14)
    at DefaultLoader.loadTemplate (http://localhost:9000/scripts/vendor-bundle.js:13770:19)
    at ensureRegistryEntry (http://localhost:9000/scripts/vendor-bundle.js:21772:19)
    at ViewEngine.loadViewFactory (http://localhost:9000/scripts/vendor-bundle.js:21840:14)
    at ConventionalViewStrategy.loadViewFactory (http://localhost:9000/scripts/vendor-bundle.js:19230:25)
    at HtmlBehaviorResource.load (http://localhost:9000/scripts/vendor-bundle.js:22619:29)
    at ResourceDescription.load (http://localhost:9000/scripts/vendor-bundle.js:21659:28)
    at ResourceModule.load (http://localhost:9000/scripts/vendor-bundle.js:21601:25)
    at http://localhost:9000/scripts/vendor-bundle.js:21971:43
From previous event:
    at ViewEngine.importViewResources (http://localhost:9000/scripts/vendor-bundle.js:21940:52)
    at http://localhost:9000/scripts/vendor-bundle.js:12870:25
From previous event:
    at loadResources (http://localhost:9000/scripts/vendor-bundle.js:12861:9)
    at http://localhost:9000/scripts/vendor-bundle.js:12938:16
    at next (http://localhost:9000/scripts/vendor-bundle.js:12818:32)
    at runTasks (http://localhost:9000/scripts/vendor-bundle.js:12824:12)
    at http://localhost:9000/scripts/vendor-bundle.js:13104:18
From previous event:
    at http://localhost:9000/scripts/vendor-bundle.js:13103:23
From previous event:
    at FrameworkConfiguration.apply (http://localhost:9000/scripts/vendor-bundle.js:13088:44)
    at Aurelia.start (http://localhost:9000/scripts/vendor-bundle.js:12704:39)
    at Object.configure (http://localhost:9000/scripts/app-bundle.js:85:17)
    at http://localhost:9000/scripts/vendor-bundle.js:11598:29
From previous event:
    at config (http://localhost:9000/scripts/vendor-bundle.js:11593:56)
    at http://localhost:9000/scripts/vendor-bundle.js:11629:14
From previous event:
    at bootstrap (http://localhost:9000/scripts/vendor-bundle.js:11628:26)
    at http://localhost:9000/scripts/vendor-bundle.js:11615:9
    at <anonymous>
From previous event:
    at run (http://localhost:9000/scripts/vendor-bundle.js:11610:61)
    at Object.<anonymous> (http://localhost:9000/scripts/vendor-bundle.js:11635:37)
    at Object.execCb (http://localhost:9000/scripts/vendor-bundle.js:5485:33)
    at Module.check (http://localhost:9000/scripts/vendor-bundle.js:4672:51)
    at Module.enable (http://localhost:9000/scripts/vendor-bundle.js:4965:22)
    at Object.enable (http://localhost:9000/scripts/vendor-bundle.js:5346:39)
    at Module.<anonymous> (http://localhost:9000/scripts/vendor-bundle.js:4950:33)
    at http://localhost:9000/scripts/vendor-bundle.js:3923:23
    at each (http://localhost:9000/scripts/vendor-bundle.js:3848:31)
    at Module.enable (http://localhost:9000/scripts/vendor-bundle.js:4902:17)
    at Module.init (http://localhost:9000/scripts/vendor-bundle.js:4577:26)
    at http://localhost:9000/scripts/vendor-bundle.js:5249:36
```

**Expected/desired behavior:**
The application should work as usual

**Comment by heikomat** [comment]
#313 seems to be the exact same problem, but #313 has a clean reproduction-setup, while this isse doesn't. if #313 is verbose enough to fond the bug, i suggest closing this issue in favour of the other one

**Comment by JeroenVinke** [comment]
@heikomat can you update to 1.5.1 and see if it works? thanks

**Comment by enrico-padovani** [comment]
I have an error too after update. Here's the message: "Unhandled rejection Error: Cannot find module './aurelia-templating-router/router-view.html'." it seems related to bluebird.

[error.zip](https://github.com/aurelia/templating-resources/files/1351883/error.zip)

It works again if I stick to `aurelia-templating-resources: "1.4.0"` AND `aurelia-templating-router: "1.1.0"`.

I'm using webpack 2.1.0-beta.22

**Comment by StrahilKazlachev** [comment]
@enrico-padovani Did you try `1.5.1`?

**Comment by enrico-padovani** [comment]
Yes i did

**Comment by JeroenVinke** [comment]
I've updated a webpack skeleton entirely and wasn't able to reproduce this. Could you try and see what triggers it @enrico-padovani ? If possible please post:

- npm version
- nodejs version
- exact versions of libraries that you use (npm ls --depth 1)

That way we can compare since there's someone else with the same problem: https://github.com/aurelia/templating-router/issues/63

**Comment by enrico-padovani** [comment]
Here you have it:
npm 5.4.2
node v6.11.2
[deps.zip](https://github.com/aurelia/templating-resources/files/1353876/deps.zip)

**Comment by JeroenVinke** [comment]
Make sure to remove the package-lock.json (or yarn.lock) from the project directory before you run `npm install`. We've had a few reports lately where updating libraries was causing issues because of the lock files

**Comment by bigopon** [comment]
@heikomat @enrico-padovani I think we have resolved this issues with latest releases of framework modules where dependencies mismatch is sort-of eliminated (it may still happen if 3rd party plugin is having different version of aurelia-binding)

I'll close this for now. please feel free to reopen/ open a new one if you still encounter this.
